spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: "jdbc:postgresql://localhost:5433/"
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        sql:
          init:
            mode: always
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  messages:
    basename: error
    encoding: UTF-8
    fallback-to-system-locale: false
    use-code-as-default-message: false
jwt:
  secret: ""
  expiration: 86400000
attach:
  upload:
    folder: attaches
  url: http://localhost:8080/api/
telegram:
  bot:
    token: ""
    username: ""